name: zx_tape_player
description: ZX Tape Player makes able uploading of TAP/TZX files to ZX Spectrum compatible computers.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.10+117

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  path: ^1.8.0
  flutter_typeahead: ^3.0.0-nullsafety.0
  package_info_plus: ^1.4.0
  sprintf: ^6.0.0
  http: ^0.13.0
  easy_localization: ^3.0.0
  file_picker: ^4.5.1
  app_center_bundle_sdk: ^0.0.2
  avatar_abc: ^1.0.6
  cached_network_image: ^3.0.0-nullsafety
  pull_to_refresh: ^2.0.0
  carousel_slider: ^4.0.0
  just_audio: ^0.9.20
  flutter_spinkit: ^5.0.0
  rxdart: ^0.27.1
  crypto: ^3.0.0
  get_it: ^7.1.3
  url_launcher: ^6.0.3
  marquee_widget: ^1.0.0
  zx_tape_to_wav: ^3.1.0+12
  flutter_mute: ^0.0.1
  shared_preferences: ^2.0.0
  flutter_statusbarcolor_ns: ^0.4.0-nullsafety
  internet_connection_checker: ^0.0.1
  wakelock: ^0.6.1+2
  volume_controller: ^2.0.0
  share_plus: ^4.0.3
  permission_handler: ^9.2.0
  in_app_review: ^2.0.1


#dependency_overrides:
#  http: ^0.12.2
#  args: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: ^0.9.0
  #flutter_automation: ^1.4.0
  flutter_native_splash: ^2.1.3+1
  build_runner: ^2.0.5

# Run command to update icons: flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icons/launcher/ios.png"
  image_path_android: "assets/icons/launcher/android.png"
  adaptive_icon_foreground: "assets/icons/launcher/android-foreground.png"
  adaptive_icon_background: "assets/icons/launcher/android-background.png"

flutter_native_splash:
  color: "#546B7F"
  fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/splash/logo.png
    - assets/images/splash/spool.png
    - assets/images/home/search-icon.png
    - assets/translations/
    - assets/sounds/empty.wav

  fonts:
    - family: ZxSpectrum
      fonts:
        - asset: assets/fonts/zx_spectrum-7.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
