# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do
  desc "Building iOS alpha"
  lane :ios_appcenter do
#     appcenter_fetch_devices(
#       api_token: "34187ea29462e406f39a06dacffffca336a0afb1",
#       owner_name: "semack-owd8",
#       app_name: "ZxTapePlayer.iOS",
#       destinations: "Testers", # Default is 'Collaborators', use '*' for all distribution groups
#       devices_file: "devices.txt" # Default. If you customize, the extension must be .txt
#     )

    appcenter_upload(
      api_token: "ca718e714c8901599a658c4d0572ae809c9e97b3",
      owner_name: "semack-owd8",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: "ZxTapePlayer.iOS",
      file: "../uild/ios/iphoneos/app.ipa,
      notify_testers: false # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end
end
