default_platform(:android)


platform :android do
  desc "Submit a new Android Beta Build to AppCenter"
  lane :beta do
    appcenter_upload(
      file: "../build/app/outputs/flutter-apk/app-release.apk",
      notify_testers: true
    )
  end
end
