default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    upload_to_play_store(
        aab: "build/app/outputs/bundle/release/app-release.aab",
        track: "beta",
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
    )
  end

  desc "Submit a new version to the Google Play"
  lane :production do
    upload_to_play_store(
         aab: "build/app/outputs/bundle/release/app-release.aab",
         track: "production",
     )
  end
end
